// Mocks generated by Mockito 5.0.16 from annotations
// in tv_series/test/presentation/pages/tv_series_detail_page_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i8;

import 'package:bloc/bloc.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tv_series/domain/usecases/get_tv_series_detail.dart' as _i2;
import 'package:tv_series/domain/usecases/get_tv_series_recommendations.dart'
    as _i3;
import 'package:tv_series/domain/usecases/get_watchlist_tv_series_status.dart'
    as _i4;
import 'package:tv_series/domain/usecases/remove_watchlist_tv_series.dart'
    as _i6;
import 'package:tv_series/domain/usecases/save_watchlist_tv_series.dart' as _i5;
import 'package:tv_series/presentation/bloc/tv_series_detail/tv_series_detail_bloc.dart'
    as _i7;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeGetTvSeriesDetail_0 extends _i1.Fake
    implements _i2.GetTvSeriesDetail {}

class _FakeGetTvSeriesRecommendations_1 extends _i1.Fake
    implements _i3.GetTvSeriesRecommendations {}

class _FakeGetWatchlistTvSeriesStatus_2 extends _i1.Fake
    implements _i4.GetWatchlistTvSeriesStatus {}

class _FakeSaveWatchlistTvSeries_3 extends _i1.Fake
    implements _i5.SaveWatchlistTvSeries {}

class _FakeRemoveWatchlistTvSeries_4 extends _i1.Fake
    implements _i6.RemoveWatchlistTvSeries {}

class _FakeTvSeriesDetailState_5 extends _i1.Fake
    implements _i7.TvSeriesDetailState {}

class _FakeStreamSubscription_6<T> extends _i1.Fake
    implements _i8.StreamSubscription<T> {}

/// A class which mocks [TvSeriesDetailBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesDetailBloc extends _i1.Mock
    implements _i7.TvSeriesDetailBloc {
  MockTvSeriesDetailBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetTvSeriesDetail get getTvSeriesDetail =>
      (super.noSuchMethod(Invocation.getter(#getTvSeriesDetail),
          returnValue: _FakeGetTvSeriesDetail_0()) as _i2.GetTvSeriesDetail);
  @override
  _i3.GetTvSeriesRecommendations get getTvSeriesRecommendations =>
      (super.noSuchMethod(Invocation.getter(#getTvSeriesRecommendations),
              returnValue: _FakeGetTvSeriesRecommendations_1())
          as _i3.GetTvSeriesRecommendations);
  @override
  _i4.GetWatchlistTvSeriesStatus get getWatchlistTvSeriesStatus =>
      (super.noSuchMethod(Invocation.getter(#getWatchlistTvSeriesStatus),
              returnValue: _FakeGetWatchlistTvSeriesStatus_2())
          as _i4.GetWatchlistTvSeriesStatus);
  @override
  _i5.SaveWatchlistTvSeries get saveWatchlist =>
      (super.noSuchMethod(Invocation.getter(#saveWatchlist),
              returnValue: _FakeSaveWatchlistTvSeries_3())
          as _i5.SaveWatchlistTvSeries);
  @override
  _i6.RemoveWatchlistTvSeries get removeWatchlist =>
      (super.noSuchMethod(Invocation.getter(#removeWatchlist),
              returnValue: _FakeRemoveWatchlistTvSeries_4())
          as _i6.RemoveWatchlistTvSeries);
  @override
  _i7.TvSeriesDetailState get state => (super.noSuchMethod(
      Invocation.getter(#state),
      returnValue: _FakeTvSeriesDetailState_5()) as _i7.TvSeriesDetailState);
  @override
  _i8.Stream<_i7.TvSeriesDetailState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i7.TvSeriesDetailState>.empty())
          as _i8.Stream<_i7.TvSeriesDetailState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  void add(_i7.TvSeriesDetailEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  void onEvent(_i7.TvSeriesDetailEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  _i8.Stream<_i9.Transition<_i7.TvSeriesDetailEvent, _i7.TvSeriesDetailState>>
      transformEvents(
              _i8.Stream<_i7.TvSeriesDetailEvent>? events,
              _i9.TransitionFunction<_i7.TvSeriesDetailEvent, _i7.TvSeriesDetailState>?
                  transitionFn) =>
          (super.noSuchMethod(
                  Invocation.method(#transformEvents, [events, transitionFn]),
                  returnValue:
                      Stream<_i9.Transition<_i7.TvSeriesDetailEvent, _i7.TvSeriesDetailState>>.empty())
              as _i8.Stream<
                  _i9.Transition<_i7.TvSeriesDetailEvent, _i7.TvSeriesDetailState>>);
  @override
  void emit(_i7.TvSeriesDetailState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void on<E extends _i7.TvSeriesDetailEvent>(
          _i9.EventHandler<E, _i7.TvSeriesDetailState>? handler,
          {_i9.EventTransformer<E>? transformer}) =>
      super.noSuchMethod(
          Invocation.method(#on, [handler], {#transformer: transformer}),
          returnValueForMissingStub: null);
  @override
  _i8.Stream<_i7.TvSeriesDetailState> mapEventToState(
          _i7.TvSeriesDetailEvent? event) =>
      (super.noSuchMethod(Invocation.method(#mapEventToState, [event]),
              returnValue: Stream<_i7.TvSeriesDetailState>.empty())
          as _i8.Stream<_i7.TvSeriesDetailState>);
  @override
  void onTransition(
          _i9.Transition<_i7.TvSeriesDetailEvent, _i7.TvSeriesDetailState>?
              transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i8.Stream<_i9.Transition<_i7.TvSeriesDetailEvent, _i7.TvSeriesDetailState>>
      transformTransitions(
              _i8.Stream<_i9.Transition<_i7.TvSeriesDetailEvent, _i7.TvSeriesDetailState>>?
                  transitions) =>
          (super.noSuchMethod(
                  Invocation.method(#transformTransitions, [transitions]),
                  returnValue:
                      Stream<_i9.Transition<_i7.TvSeriesDetailEvent, _i7.TvSeriesDetailState>>.empty())
              as _i8.Stream<
                  _i9.Transition<_i7.TvSeriesDetailEvent, _i7.TvSeriesDetailState>>);
  @override
  _i8.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i8.Future<void>);
  @override
  _i8.StreamSubscription<_i7.TvSeriesDetailState> listen(
          void Function(_i7.TvSeriesDetailState)? onData,
          {Function? onError,
          void Function()? onDone,
          bool? cancelOnError}) =>
      (super.noSuchMethod(
              Invocation.method(#listen, [
                onData
              ], {
                #onError: onError,
                #onDone: onDone,
                #cancelOnError: cancelOnError
              }),
              returnValue: _FakeStreamSubscription_6<_i7.TvSeriesDetailState>())
          as _i8.StreamSubscription<_i7.TvSeriesDetailState>);
  @override
  void onChange(_i9.Change<_i7.TvSeriesDetailState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}
