// Mocks generated by Mockito 5.0.16 from annotations
// in core/test/presentation/pages/on_the_air_tv_series_page_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:bloc/bloc.dart' as _i5;
import 'package:core/domain/usecases/get_on_the_air_tv_series.dart' as _i2;
import 'package:core/presentation/bloc/on_the_air_tv_series/on_the_air_tv_series_bloc.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeGetOnTheAirTvSeries_0 extends _i1.Fake
    implements _i2.GetOnTheAirTvSeries {}

class _FakeOnTheAirTvSeriesState_1 extends _i1.Fake
    implements _i3.OnTheAirTvSeriesState {}

class _FakeStreamSubscription_2<T> extends _i1.Fake
    implements _i4.StreamSubscription<T> {}

/// A class which mocks [OnTheAirTvSeriesBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockOnTheAirTvSeriesBloc extends _i1.Mock
    implements _i3.OnTheAirTvSeriesBloc {
  MockOnTheAirTvSeriesBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetOnTheAirTvSeries get getOnTheAirTvSeries => (super.noSuchMethod(
      Invocation.getter(#getOnTheAirTvSeries),
      returnValue: _FakeGetOnTheAirTvSeries_0()) as _i2.GetOnTheAirTvSeries);
  @override
  _i3.OnTheAirTvSeriesState get state =>
      (super.noSuchMethod(Invocation.getter(#state),
              returnValue: _FakeOnTheAirTvSeriesState_1())
          as _i3.OnTheAirTvSeriesState);
  @override
  _i4.Stream<_i3.OnTheAirTvSeriesState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i3.OnTheAirTvSeriesState>.empty())
          as _i4.Stream<_i3.OnTheAirTvSeriesState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  void add(_i3.OnTheAirTvSeriesEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  void onEvent(_i3.OnTheAirTvSeriesEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  _i4.Stream<_i5.Transition<_i3.OnTheAirTvSeriesEvent, _i3.OnTheAirTvSeriesState>>
      transformEvents(
              _i4.Stream<_i3.OnTheAirTvSeriesEvent>? events,
              _i5.TransitionFunction<_i3.OnTheAirTvSeriesEvent,
                      _i3.OnTheAirTvSeriesState>?
                  transitionFn) =>
          (super.noSuchMethod(
              Invocation.method(#transformEvents, [events, transitionFn]),
              returnValue:
                  Stream<_i5.Transition<_i3.OnTheAirTvSeriesEvent, _i3.OnTheAirTvSeriesState>>.empty()) as _i4
              .Stream<_i5.Transition<_i3.OnTheAirTvSeriesEvent, _i3.OnTheAirTvSeriesState>>);
  @override
  void emit(_i3.OnTheAirTvSeriesState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void on<E extends _i3.OnTheAirTvSeriesEvent>(
          _i5.EventHandler<E, _i3.OnTheAirTvSeriesState>? handler,
          {_i5.EventTransformer<E>? transformer}) =>
      super.noSuchMethod(
          Invocation.method(#on, [handler], {#transformer: transformer}),
          returnValueForMissingStub: null);
  @override
  _i4.Stream<_i3.OnTheAirTvSeriesState> mapEventToState(
          _i3.OnTheAirTvSeriesEvent? event) =>
      (super.noSuchMethod(Invocation.method(#mapEventToState, [event]),
              returnValue: Stream<_i3.OnTheAirTvSeriesState>.empty())
          as _i4.Stream<_i3.OnTheAirTvSeriesState>);
  @override
  void onTransition(
          _i5.Transition<_i3.OnTheAirTvSeriesEvent, _i3.OnTheAirTvSeriesState>?
              transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i4.Stream<_i5.Transition<_i3.OnTheAirTvSeriesEvent, _i3.OnTheAirTvSeriesState>>
      transformTransitions(
              _i4.Stream<_i5.Transition<_i3.OnTheAirTvSeriesEvent, _i3.OnTheAirTvSeriesState>>?
                  transitions) =>
          (super.noSuchMethod(
                  Invocation.method(#transformTransitions, [transitions]),
                  returnValue:
                      Stream<_i5.Transition<_i3.OnTheAirTvSeriesEvent, _i3.OnTheAirTvSeriesState>>.empty())
              as _i4.Stream<
                  _i5.Transition<_i3.OnTheAirTvSeriesEvent, _i3.OnTheAirTvSeriesState>>);
  @override
  _i4.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  _i4.StreamSubscription<_i3.OnTheAirTvSeriesState> listen(
          void Function(_i3.OnTheAirTvSeriesState)? onData,
          {Function? onError,
          void Function()? onDone,
          bool? cancelOnError}) =>
      (super.noSuchMethod(
              Invocation.method(#listen, [
                onData
              ], {
                #onError: onError,
                #onDone: onDone,
                #cancelOnError: cancelOnError
              }),
              returnValue:
                  _FakeStreamSubscription_2<_i3.OnTheAirTvSeriesState>())
          as _i4.StreamSubscription<_i3.OnTheAirTvSeriesState>);
  @override
  void onChange(_i5.Change<_i3.OnTheAirTvSeriesState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}
