// Mocks generated by Mockito 5.0.16 from annotations
// in core/test/presentation/pages/top_rated_tv_series_page_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:bloc/bloc.dart' as _i5;
import 'package:core/domain/usecases/get_top_rated_tv_series.dart' as _i2;
import 'package:core/presentation/bloc/top_rated_tv_series/top_rated_tv_series_bloc.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeGetTopRatedTvSeries_0 extends _i1.Fake
    implements _i2.GetTopRatedTvSeries {}

class _FakeTopRatedTvSeriesState_1 extends _i1.Fake
    implements _i3.TopRatedTvSeriesState {}

class _FakeStreamSubscription_2<T> extends _i1.Fake
    implements _i4.StreamSubscription<T> {}

/// A class which mocks [TopRatedTvSeriesBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockTopRatedTvSeriesBloc extends _i1.Mock
    implements _i3.TopRatedTvSeriesBloc {
  MockTopRatedTvSeriesBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetTopRatedTvSeries get getTopRatedTvSeries => (super.noSuchMethod(
      Invocation.getter(#getTopRatedTvSeries),
      returnValue: _FakeGetTopRatedTvSeries_0()) as _i2.GetTopRatedTvSeries);
  @override
  _i3.TopRatedTvSeriesState get state =>
      (super.noSuchMethod(Invocation.getter(#state),
              returnValue: _FakeTopRatedTvSeriesState_1())
          as _i3.TopRatedTvSeriesState);
  @override
  _i4.Stream<_i3.TopRatedTvSeriesState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i3.TopRatedTvSeriesState>.empty())
          as _i4.Stream<_i3.TopRatedTvSeriesState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  void add(_i3.TopRatedTvSeriesEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  void onEvent(_i3.TopRatedTvSeriesEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  _i4.Stream<_i5.Transition<_i3.TopRatedTvSeriesEvent, _i3.TopRatedTvSeriesState>>
      transformEvents(
              _i4.Stream<_i3.TopRatedTvSeriesEvent>? events,
              _i5.TransitionFunction<_i3.TopRatedTvSeriesEvent,
                      _i3.TopRatedTvSeriesState>?
                  transitionFn) =>
          (super.noSuchMethod(
              Invocation.method(#transformEvents, [events, transitionFn]),
              returnValue:
                  Stream<_i5.Transition<_i3.TopRatedTvSeriesEvent, _i3.TopRatedTvSeriesState>>.empty()) as _i4
              .Stream<_i5.Transition<_i3.TopRatedTvSeriesEvent, _i3.TopRatedTvSeriesState>>);
  @override
  void emit(_i3.TopRatedTvSeriesState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void on<E extends _i3.TopRatedTvSeriesEvent>(
          _i5.EventHandler<E, _i3.TopRatedTvSeriesState>? handler,
          {_i5.EventTransformer<E>? transformer}) =>
      super.noSuchMethod(
          Invocation.method(#on, [handler], {#transformer: transformer}),
          returnValueForMissingStub: null);
  @override
  _i4.Stream<_i3.TopRatedTvSeriesState> mapEventToState(
          _i3.TopRatedTvSeriesEvent? event) =>
      (super.noSuchMethod(Invocation.method(#mapEventToState, [event]),
              returnValue: Stream<_i3.TopRatedTvSeriesState>.empty())
          as _i4.Stream<_i3.TopRatedTvSeriesState>);
  @override
  void onTransition(
          _i5.Transition<_i3.TopRatedTvSeriesEvent, _i3.TopRatedTvSeriesState>?
              transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i4.Stream<_i5.Transition<_i3.TopRatedTvSeriesEvent, _i3.TopRatedTvSeriesState>>
      transformTransitions(
              _i4.Stream<_i5.Transition<_i3.TopRatedTvSeriesEvent, _i3.TopRatedTvSeriesState>>?
                  transitions) =>
          (super.noSuchMethod(
                  Invocation.method(#transformTransitions, [transitions]),
                  returnValue:
                      Stream<_i5.Transition<_i3.TopRatedTvSeriesEvent, _i3.TopRatedTvSeriesState>>.empty())
              as _i4.Stream<
                  _i5.Transition<_i3.TopRatedTvSeriesEvent, _i3.TopRatedTvSeriesState>>);
  @override
  _i4.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  _i4.StreamSubscription<_i3.TopRatedTvSeriesState> listen(
          void Function(_i3.TopRatedTvSeriesState)? onData,
          {Function? onError,
          void Function()? onDone,
          bool? cancelOnError}) =>
      (super.noSuchMethod(
              Invocation.method(#listen, [
                onData
              ], {
                #onError: onError,
                #onDone: onDone,
                #cancelOnError: cancelOnError
              }),
              returnValue:
                  _FakeStreamSubscription_2<_i3.TopRatedTvSeriesState>())
          as _i4.StreamSubscription<_i3.TopRatedTvSeriesState>);
  @override
  void onChange(_i5.Change<_i3.TopRatedTvSeriesState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}
